-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 12:05:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CodeWeekWom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CodeWeekWom` DEFAULT CHARACTER SET utf8;
USE `CodeWeekWom`;

-- -----------------------------------------------------
-- Table `CodeWeekWom`.`Certificates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CodeWeekWom`.`Certificates` (
  `CertificateId` INTEGER NOT NULL,
  `Url` VARCHAR(2048) NOT NULL COLLATE latin1_general_ci,
  `RegistrationDate` DATETIME NOT NULL,

  PRIMARY KEY (`CertificateId`)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
